version: '3.8'

services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gateway_registry
    command: uvicorn gateway_registry.gateway_registry:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    restart: always

  bukin-3d:
    build: .
    container_name: 3d_bukin_service
    command: uvicorn optimization_functions.3d_Bukin_function:app --host 0.0.0.0 --port 8505
    ports:
      - "8505:8505"
    depends_on:
      - gateway
    restart: always

  rastrigin-3d:
    build: .
    container_name: 3d_rastrigin_service
    command: uvicorn optimization_functions.3d_Rastrigin_function:app --host 0.0.0.0 --port 8501
    ports:
      - "8501:8501"
    depends_on:
      - gateway
    restart: always

  rosenbrock-3d:
    build: .
    container_name: 3d_rosenbrock_service
    command: uvicorn optimization_functions.3d_Rosenbrock_function:app --host 0.0.0.0 --port 8502
    ports:
      - "8502:8502"
    depends_on:
      - gateway
    restart: always

  schwefel-3d:
    build: .
    container_name: 3d_schwefel_service
    command: uvicorn optimization_functions.3d_Schwefel_function:app --host 0.0.0.0 --port 8503
    ports:
      - "8503:8503"
    depends_on:
      - gateway
    restart: always

  sin-3d:
    build: .
    container_name: 3d_sin_service
    command: uvicorn optimization_functions.3d_sin:app --host 0.0.0.0 --port 8504
    ports:
      - "8504:8504"
    depends_on:
      - gateway
    restart: always

  newton-2d:
    build: .
    container_name: newton_2d_service
    command: uvicorn server_graphics.newton_2d:app --host 0.0.0.0 --port 8601
    ports:
      - "8601:8601"
    depends_on:
      - gateway
    restart: always

  newton-3d:
    build: .
    container_name: newton_3d_service
    command: uvicorn server_graphics.newton_3d:app --host 0.0.0.0 --port 8602
    ports:
      - "8602:8602"
    depends_on:
      - gateway
    restart: always

  parabola-base:
    build: .
    container_name: parabola_base_service
    command: python server_graphics/parabola.py
    depends_on:
      - gateway
    restart: always

  parabola-service:
    build: .
    container_name: parabola_websocket_service
    command: uvicorn server_graphics.parabola_service:app --host 0.0.0.0 --port 8603
    ports:
      - "8603:8603"
    depends_on:
      - gateway
    restart: always

  tahometr:
    build: .
    container_name: tahometr_service
    command: uvicorn server_graphics.tahometr:app --host 0.0.0.0 --port 8604
    ports:
      - "8604:8604"
    depends_on:
      - gateway
    restart: always

  temperature-boiler:
    build: .
    container_name: temperature_boiler_service
    command: uvicorn server_graphics.temperature_boiler:app --host 0.0.0.0 --port 8605
    ports:
      - "8605:8605"
    depends_on:
      - gateway
    restart: always

  temperature-sensor:
    build: .
    container_name: temperature_sensor_service
    command: uvicorn server_graphics.tempurature_sensor:app --host 0.0.0.0 --port 8606
    ports:
      - "8606:8606"
    depends_on:
      - gateway
    restart: always

  trubka-pito:
    build: .
    container_name: trubka_pito_service
    command: uvicorn server_graphics.trubka_Pito:app --host 0.0.0.0 --port 8607
    ports:
      - "8607:8607"
    depends_on:
      - gateway
    restart: always

  table-service:
    build: .
    container_name: table_data_service
    command: uvicorn server_tables.table_service:app --host 0.0.0.0 --port 8701
    ports:
      - "8701:8701"
    depends_on:
      - gateway
    restart: always