version: '3.8'

services:
  gateway_registry:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app/servers
    ports:
      - "8000:8000"
    command: uvicorn servers.gateway_registry.gateway_registry:app --host 0.0.0.0 --port 8000 --reload